version: '3'

services:
  traefik:
    image: traefik:v2.5
    network_mode: "host"
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443" 
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      ################################################ insert your email here ################
      - "--certificatesresolvers.myresolver.acme.email=thebaultyoann56@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  mariadb:
    build:
      context: ./MariaDB/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
    ###### modify this password, remember it and delete it from this file afterwards ######
      - MYSQL_ROOT_PASSWORD=lol
    container_name: mariadb
  
  fastapi-user:
    build:
      context: ./API_User/
      dockerfile: Dockerfile
    volumes:
      - "./files:/files"
    labels:
      - 'traefik.enable=true'
      ####################################### insert your domain name here ################
      - 'traefik.http.routers.fastapi.rule=Host(`api.astrolabium.gotdns.ch`) && PathPrefix(`/`)'
      - 'traefik.http.routers.fastapi.entrypoints=websecure'
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - 'traefik.http.routers.fastapi.tls=true'
      - 'traefik.http.services.fastapi.loadbalancer.server.port=8000'
    container_name: fastapi-user
    depends_on:
      - mariadb
    command: bash -c "sleep 10 && gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    restart: "on-failure:5"

  fastapi-admin:
    build:
      context: ./API_Admin/
      dockerfile: Dockerfile
    volumes:
      - "./files:/files"
    labels:
      - 'traefik.enable=true'
      ####################################### insert your domain name here ################
      - 'traefik.http.routers.fastapi.rule=Host(`admin.astrolabium.gotdns.ch`) && PathPrefix(`/`)'
      - 'traefik.http.routers.fastapi.entrypoints=websecure'
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - 'traefik.http.routers.fastapi.tls=true'
      - 'traefik.http.services.fastapi.loadbalancer.server.port=8001'
    container_name: fastapi-admin 
    depends_on:
      - mariadb
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8001"
    restart: "on-failure:5"

