version: '3'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  mariadb:
    build:
      context: ./MariaDB/
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lol
    container_name: mariadb
  
  api:
    build:
      context: ./API/
      dockerfile: Dockerfile
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.local`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
    container_name: api
    depends_on:
      - mariadb
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: "on-failure:5"
networks:
  mynetwork:
