version: '3'

services:
  traefik:
    image: traefik:v2.5
    network_mode: "host"
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443" 
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      ################################################ insert your email here ################
      - "--certificatesresolvers.myresolver.acme.email="thebaultyoann56@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  mariadb:
    build:
      context: ./MariaDB/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
     ##### insert mariadb root password here #####
      - MYSQL_ROOT_PASSWORD=
    container_name: mariadb

  fastapi-user:
    build:
      context: ./API_User/
      dockerfile: Dockerfile
    volumes:
      - "./files_user:/files"
    labels:
      - 'traefik.enable=true'
      ####################################### insert your domain name here ################
      - 'traefik.http.routers.fastapi-user.rule=Host(`api.astrolabium.io`) && PathPrefix(`/`)'
      - 'traefik.http.routers.fastapi-user.entrypoints=websecure'
      - "traefik.http.routers.fastapi-user.tls.certresolver=myresolver"
      - 'traefik.http.routers.fastapi-user.tls=true'
      - 'traefik.http.services.fastapi-user.loadbalancer.server.port=8000'
    container_name: fastapi-user
    depends_on:
      - mariadb
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 240"
    restart: "on-failure:5"


  fastapi-admin:
    build:
      context: ./API_Admin/
      dockerfile: Dockerfile
    volumes:
      - "./files:/files"
    labels:
      - 'traefik.enable=true'
      ####################################### insert your domain name here ################
      - 'traefik.http.routers.fastapi-admin.rule=Host(`admin.astrolabium.io`) && PathPrefix(`/`)'
      - 'traefik.http.routers.fastapi-admin.entrypoints=websecure'
      - "traefik.http.routers.fastapi-admin.tls.certresolver=myresolver"
      - 'traefik.http.routers.fastapi-admin.tls=true'
      - 'traefik.http.services.fastapi-admin.loadbalancer.server.port=8001'
    container_name: fastapi-admin 
    depends_on:
      - mariadb
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8001"
    restart: "on-failure:5"

